[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.12", features = ["transport"] }
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
tower = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
futures-core = "0.3"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

anyhow = "1.0.100"
uuid = { version = "1", features = ["v4"] }

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"

[[bin]]
name = "server"
path = "src/server.rs"


[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "engine"
path = "src/grpc_server.rs"
